### ISSUE TITLE
Does hotstart initialize the active set?

### ISSUE THREAD

**Issue by jlack1987** [coin-or/qpOASES#125]
This is more just a question about functionality. Whenever `hotstart` is called, does this also initialize the active set to the one from the previous solution? I saw in the manual that you can give an initial guess for the active set, but if calling `hotstart` already does this then I don't want to waste my time

**Comment by apotschka** [comment]
`hotstart` already does this. Actually, it does even more: It reuses existing matrix decompositions from the last call. If you supply an initial active set manually, it will discard these decompositions, which will lead to worse performance.

**Comment by jlack1987** [comment]
Thanks for the clarification :+1:
