### ISSUE TITLE
Optimal solution off compared to analytical solution when Equality constraints are used 

### ISSUE THREAD

**Issue by MaximilianDio** [coin-or/qpOASES#134]
Hi, while trying to solve a general QP problem I have some issues. Therefore, I reduced the problem to only contain equality constraints, where I can calculate the solution analytically. However, when I try to solve the problem with qpOASES, the solution is completely off although the solution is found.

The Problem
min_x 1/2*x^T H x + x^T*g
s.t. A*x+b=0

The analytical solution including the dual Soulution:

[H A^T; A 0]⁻¹*[-g;-b]=[x,y]

My qp setup using Eigen:
```
lbA = -b;
ubA = -b;

qproblem.init(H.data(),g.data(), A.data(),nullptr,nullptr,lbA.data(),ubA.data(),nWSR,&cputime)

qproblem.getPrimalSolution(xOpt);
qproblem.getDualSolution(yOpt);

```

I have no Idea why I get a completely different solution compared to the analytical solutions. Any Suggestions?

**Comment by apotschka** [comment]
By convention, qpOASES uses a negative sign in the Lagrangian (see manual p. 15, footnote). Does swapping the sign of `yOpt` yield your expected solution?

**Comment by MaximilianDio** [comment]
I had a look at the dual solution, and it is zero.

**Comment by MaximilianDio** [comment]
Hey, I found my problem. I thought you only need to allocate n_C elements for yOpt because I do not include the basic bounds (nullptr). However, this will overwrite the primal solution. When I allocate enough space everything works fine.
