### ISSUE TITLE
I would like to run qpOASES on embedded hardware but cannot compile C++ code. What shall I do?

### ISSUE THREAD

**Issue by svigerske** [coin-or/qpOASES#18]
Issue created by migration from Trac.

Original creator: ferreau

Original creation time: 2014-07-24 10:28:21

Assignee: ferreau

Version: 

The official releases of qpOASES are written and maintained in a kind of "C++ light", i.e. they do not make use of some advanced features of this programming language (like templates or the STL). So you might check if there exist a suitable rudimentary C++ compiler for your specific embedded system. Moreover, an inofficial plain ANSI C translation of qpOASES 1.2 is available upon request.

**Comment by svigerske** [comment]
Comment by ferreau created at 2014-07-24 10:28:52

Resolution: fixed

**Comment by mnissov** [comment]
> Moreover, an inofficial plain ANSI C translation of qpOASES 1.2 is available upon request

Is this still available?
